import re
import typer
import difflib
from pathlib import Path
from typing import Dict

from auto.types import ROOT, SPEC_DIR, RSC, Language, Spec, DOCS_ROOT, ISSUE_TEMPLATES_MARKDOWN, GITHUB_ISSUE_TEMPLATE_DIR, SpecStatus
from yaml import safe_dump as write_yaml

app = typer.Typer(
    name="doc-manager",
    help="Manage Kintsu documentation schemas and specifications.",
)

TEMPLATE_PATH = ROOT / "templates"

TEMPLATES = {
    "ad": TEMPLATE_PATH / "ad.md",
}


@app.command()
def spec_guide():
    lang = Language.get()
    lang.write_spec()


@app.command()
def collect_refs():
    """Collect cross-references between specifications and write to references.yaml"""
    # Pattern to match spec references like [RFC-0001](/specs/rfc/rfc-0001)
    # Case insensitive for spec kind
    pattern = re.compile(
        r'\[([A-Z]+)-0*(\d+)\]\(/specs/[a-z]+/[a-z]+-0*\d+\)',
        re.IGNORECASE
    )

    references: dict[str, set[str]] = {}

    # Walk all markdown files in specs directory
    for spec_file in SPEC_DIR.rglob("*.md"):
        content = spec_file.read_text()

        # Extract spec ID from filename (e.g., RFC-0001.md -> rfc-0001)
        filename = spec_file.stem  # e.g., RFC-0001
        parts = filename.split("-")
        if len(parts) == 2:
            source_kind = parts[0].lower()
            source_num = int(parts[1])
            source_id = f"{source_kind}-{source_num:04d}"

            # Find all references in this file
            matches = pattern.findall(content)
            if matches:
                refs = set()
                for kind, num in matches:
                    ref_id = f"{kind.lower()}-{int(num):04d}"
                    # Don't include self-references
                    if ref_id != source_id:
                        refs.add(ref_id)

                if refs:
                    references[source_id] = sorted(refs)

    # Write to references.yaml
    refs_path = RSC / "references.yaml"
    refs_path.write_text(
        "# @autogenerated - DO NOT EDIT\n\n" +
        write_yaml(dict(sorted(references.items())), sort_keys=False, default_flow_style=False)
    )

    print(f"Wrote references to {refs_path}")
    print(f"Collected {len(references)} specs with cross-references")


@app.command()
def new_spec(
    spec_kind: str = typer.Option(help="Specification kind ID"),
    title: str = typer.Option(help="Title of the new specification"),
    author: str = typer.Option(help="Author of the specification (github username)"),
    components: list[str] = typer.Option(
        help="Component IDs included in the specification"
    ),
):
    lang = Language.get()
    next_number = Spec.next_spec_number(spec_kind)

    spec = Spec.new(
        kind=spec_kind,
        number=next_number,
        title=title,
        author=author,
        components=components,
        version_after=lang.current_version,
    )

    lang.validate_spec(spec)

    print(f"Creating new spec {spec_kind}-{next_number} titled '{title}'")

    spec_kind_data = lang.get_spec_kind(spec_kind)
    template = spec_kind_data.template_for(lang)

    qualified_spec = f"{spec.kind}-{spec.number:04d}"

    out = spec.as_markdown_head() + template.format(
        qualified_spec=qualified_spec, **Spec.write_to_dict(spec)
    )

    path = spec.path_for()

    if not path.parent.exists():
        path.parent.mkdir()

    path.write_text(out)


@app.command()
def reference_tables(
    dry_run: bool = typer.Option(False, "--dry-run", help="Show diffs without writing files")
):
    """Update ## References sections in all specification files based on references.yaml"""

    lang = Language.get()
    refs = lang.references

    # Pattern to match the entire References section
    refs_section_pattern = re.compile(
        r'^## References\n(?:(?!^## ).*\n)*',
        re.MULTILINE
    )

    # Pattern to match existing reference lines
    ref_line_pattern = re.compile(
        r'- \[([A-Z]+-\d+)\]\(/specs/[a-z]+/[a-z]+-\d+\)',
        re.IGNORECASE
    )

    updated_count = 0

    for spec_file in SPEC_DIR.rglob("*.md"):
        content = spec_file.read_text()

        # Extract spec ID from filename
        filename = spec_file.stem
        parts = filename.split("-")
        if len(parts) != 2:
            continue

        source_kind = parts[0].lower()
        source_num = int(parts[1])
        source_id = f"{source_kind}-{source_num:04d}"

        # Check if this spec has references
        if source_id not in refs:
            continue

        # Find existing References section
        match = refs_section_pattern.search(content)
        if not match:
            # No References section found, skip
            continue

        existing_section = match.group(0)

        # Extract manually added references (ones not in references.yaml)
        existing_refs = set()
        for ref_match in ref_line_pattern.finditer(existing_section):
            ref_id = ref_match.group(1).lower()
            # Normalize to 4-digit format
            ref_parts = ref_id.split("-")
            if len(ref_parts) == 2:
                normalized = f"{ref_parts[0]}-{int(ref_parts[1]):04d}"
                existing_refs.add(normalized)

        # Get references from references.yaml
        yaml_refs = set(refs[source_id])

        # Find manually added refs (in file but not in yaml)
        manual_refs = existing_refs - yaml_refs

        # Combine: yaml refs + manual refs, sorted
        all_refs = sorted(yaml_refs | manual_refs)

        # Build new References section with proper titles
        new_section = "## References\n\n"
        for ref_id in all_refs:
            # Find the spec to get its title
            ref_parts = ref_id.split("-")
            ref_kind = ref_parts[0]
            ref_num = int(ref_parts[1])

            ref_path = SPEC_DIR / ref_kind / f"{ref_kind.upper()}-{ref_num:04d}.md"
            if ref_path.exists():
                # Extract title from the spec file
                ref_content = ref_path.read_text()
                try:
                    ref_spec = Spec.from_markdown_head(ref_content)
                    title = ref_spec.title
                except:
                    # Fallback if parsing fails
                    title = "Unknown"
            else:
                title = "Unknown"

            # Format: [RFC-0001](/specs/rfc/rfc-0001) - Title
            display_id = f"{ref_kind.upper()}-{ref_num:04d}"
            url_id = f"{ref_kind.lower()}-{ref_num:04d}"
            new_section += f"- [{display_id}](/specs/{ref_kind}/{url_id}) - {title}\n"

        new_section += "\n"

        # Replace the old References section
        new_content = refs_section_pattern.sub(new_section, content)

        if new_content != content:
            if dry_run:
                # Show diff
                old_lines = content.splitlines(keepends=True)
                new_lines = new_content.splitlines(keepends=True)
                diff = difflib.unified_diff(
                    old_lines,
                    new_lines,
                    fromfile=f"a/{spec_file.relative_to(DOCS_ROOT)}",
                    tofile=f"b/{spec_file.relative_to(DOCS_ROOT)}",
                    lineterm=""
                )
                print("".join(diff))
            else:
                spec_file.write_text(new_content)
                print(f"Updated references in {spec_file.name}")
            updated_count += 1

    if dry_run:
        print(f"\nWould update {updated_count} specification files (dry-run mode)")
    else:
        print(f"\nUpdated {updated_count} specification files")


@app.command()
def collect_specs():
    """Generate specification summary with nested sub-references"""
    lang = Language.get()
    specs = lang.specs()
    refs = lang.references

    summary = "---\n# @autogenerated - DO NOT EDIT\n\ntitle: Specifications\n---\n\n"
    by_category: dict[str, list[Spec]] = {}
    for spec in specs:
        if spec.kind in by_category:
            by_category[spec.kind].append(spec)
        else:
            by_category[spec.kind] = [spec]

    for spec_kind, specs_list in by_category.items():
        category = lang.get_spec_kind(spec_kind)

        summary += f"- [{category.name}](/specs/{spec_kind.lower()})\n"
        for spec in specs_list:
            spec_id = spec.qualified_id()
            spec_id_lower = spec_id.lower()  # Match references.yaml format
            summary += f"  - [{spec_id} - {spec.title}]({spec.url_for()})\n"

            # Add sub-references if they exist (references.yaml uses lowercase)
            if spec_id_lower in refs:
                for ref_id in refs[spec_id_lower]:
                    # Find referenced spec to get its title
                    ref_parts = ref_id.split("-")
                    ref_kind = ref_parts[0]
                    ref_num = int(ref_parts[1])

                    ref_path = SPEC_DIR / ref_kind / f"{ref_kind.upper()}-{ref_num:04d}.md"
                    if ref_path.exists():
                        try:
                            ref_content = ref_path.read_text()
                            ref_spec = Spec.from_markdown_head(ref_content)
                            title = ref_spec.title
                        except:
                            title = "Unknown"
                    else:
                        title = "Unknown"

                    display_id = f"{ref_kind.upper()}-{ref_num:04d}"
                    url = f"/specs/{ref_kind}/{ref_id}"
                    # Use 4 spaces and hyphen for proper nesting (not 6 spaces and asterisk)
                    summary += f"    - [{display_id} - {title}]({url})\n"
        summary += "\n"

    summary_path = SPEC_DIR / "../docs" / "summary.md"
    summary_path.write_text(summary)
    print(f"Wrote spec summary to {summary_path}")


@app.command()
def generate_issue_templates():
    """Generate GitHub issue templates from kintsu.yaml definitions"""
    lang = Language.get()

    # Ensure output directory exists
    GITHUB_ISSUE_TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Generating {len(lang.issue_templates)} issue templates...")

    for template in lang.issue_templates:
        yml_content = _build_template_yml(template, lang)
        output_path = GITHUB_ISSUE_TEMPLATE_DIR / f"{template.id}.yml"
        output_path.write_text(yml_content)
        print(f"  Generated {template.id}.yml")

    print(f"\nSuccessfully generated {len(lang.issue_templates)} issue templates")
    print(f"Output directory: {GITHUB_ISSUE_TEMPLATE_DIR}")


def _build_template_yml(template, lang: Language) -> str:
    """Build GitHub issue template YAML from template definition"""
    data = {
        "name": template.name,
        "description": template.description,
        "title": template.title_prefix,
        "labels": template.labels,
        "body": []
    }

    for section in template.sections:
        field = {"type": section.type}

        if section.type != "markdown":
            field["id"] = section.id
        else:
            field["id"] = section.id

        if section.type == "markdown":
            # Load markdown content from file
            if not section.markdown_file:
                raise ValueError(f"Template {template.id}, section {section.id}: markdown type requires markdown_file")

            md_path = ISSUE_TEMPLATES_MARKDOWN / section.markdown_file
            markdown_content = md_path.read_text()
            field["attributes"] = {"value": markdown_content}
        else:
            # Build attributes for other field types
            field["attributes"] = {}
            if section.label:
                field["attributes"]["label"] = section.label
            if section.description:
                field["attributes"]["description"] = section.description

            # Handle placeholder (static or from markdown file)
            if section.markdown_placeholder:
                md_path = ISSUE_TEMPLATES_MARKDOWN / section.markdown_placeholder
                placeholder_content = md_path.read_text()
                field["attributes"]["placeholder"] = placeholder_content
            elif section.placeholder:
                field["attributes"]["placeholder"] = section.placeholder

            if section.render:
                field["attributes"]["render"] = section.render

            # Handle dynamic sources
            if section.source:
                options = _build_options_from_source(section.source, section.format, lang, section.prefix_label)
                if section.type == "dropdown":
                    field["attributes"]["options"] = options
                    if section.multiple:
                        field["attributes"]["multiple"] = section.multiple
                    if section.default is not None:
                        field["attributes"]["default"] = section.default
                elif section.type == "checkboxes":
                    field["attributes"]["options"] = [{"label": opt} for opt in options]
            elif section.options:
                # Static options
                if section.type == "checkboxes":
                    field["attributes"]["options"] = [{"label": opt.label} for opt in section.options]
                else:
                    field["attributes"]["options"] = [opt.label for opt in section.options]

            # Add validations
            field["validations"] = {"required": section.required}

        data["body"].append(field)

    return write_yaml(data, sort_keys=False, default_flow_style=False)


def _build_options_from_source(source: str, format_str: str | None, lang: Language, prefix_label: bool = False) -> list[str]:
    """Build dropdown/checkbox options from Language data source"""
    if source == "components":
        items = lang.components
    elif source == "spec_kinds":
        items = lang.spec_kinds
    elif source == "spec_status":
        items = [type('obj', (), {'value': s.value})() for s in SpecStatus]
    else:
        raise ValueError(f"Unknown source: {source}")

    if not format_str:
        # Default formats
        if source == "components":
            format_str = "{id}"
        elif source == "spec_kinds":
            format_str = "{id.upper()} ({name})"
        elif source == "spec_status":
            format_str = "{value}"

    options = []
    for item in items:
        # Build namespace for format string evaluation
        ns = {}
        for attr in ['id', 'name', 'description', 'value', 'code', 'category']:
            if hasattr(item, attr):
                val = getattr(item, attr)
                ns[attr] = val
                # Support .upper() and .lower() method calls in format strings
                if isinstance(val, str):
                    ns[attr] = type('str_with_methods', (), {
                        '__str__': lambda self=val: self,
                        '__repr__': lambda self=val: self,
                        'upper': lambda self=val: self.upper(),
                        'lower': lambda self=val: self.lower(),
                    })()

        try:
            # Evaluate format string
            formatted = eval(f"f\"{format_str}\"", {"__builtins__": {}}, ns)
            if prefix_label and source == "spec_kinds":
                options.append(formatted)
            else:
                options.append(str(formatted))
        except Exception as e:
            raise ValueError(f"Error formatting with '{format_str}' for {source}: {e}")

    return options


@app.command()
def generate_issue_templates():
    """Generate GitHub issue templates from resource definitions"""
    lang = Language.get()

    # Ensure output directory exists
    GITHUB_ISSUE_TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)

    generated_count = 0
    for template in lang.issue_templates:
        yml_content = _build_template_yml(template, lang)
        output_path = GITHUB_ISSUE_TEMPLATE_DIR / f"{template.id}.yml"
        output_path.write_text(yml_content)
        print(f"Generated {output_path.relative_to(DOCS_ROOT)}")
        generated_count += 1

    print(f"\nSuccessfully generated {generated_count} issue template(s)")


def _build_template_yml(template, lang: Language) -> str:
    """Build GitHub issue template YAML from template definition"""
    data = {
        "name": template.name,
        "description": template.description,
        "title": template.title_prefix,
        "labels": template.labels,
        "body": []
    }

    for section in template.sections:
        field = {"type": section.type, "id": section.id}

        if section.type == "markdown":
            # Load markdown content from file
            md_path = ISSUE_TEMPLATES_MARKDOWN / section.markdown_file
            markdown_content = md_path.read_text().strip()
            field["attributes"] = {"value": markdown_content}
        else:
            field["attributes"] = {}

            if section.label:
                field["attributes"]["label"] = section.label
            if section.description:
                field["attributes"]["description"] = section.description

            # Handle placeholder - either from markdown file or static
            if section.markdown_placeholder:
                placeholder_path = ISSUE_TEMPLATES_MARKDOWN / section.markdown_placeholder
                field["attributes"]["placeholder"] = placeholder_path.read_text().strip()
            elif section.placeholder:
                field["attributes"]["placeholder"] = section.placeholder

            if section.render:
                field["attributes"]["render"] = section.render

            # Handle dynamic sources and static options
            if section.source:
                options = _generate_options(section, lang)
                if section.type == "dropdown":
                    field["attributes"]["options"] = options
                    if section.multiple:
                        field["attributes"]["multiple"] = section.multiple
                elif section.type == "checkboxes":
                    field["attributes"]["options"] = [{"label": opt} for opt in options]
            elif section.options:
                # Static options for checkboxes
                field["attributes"]["options"] = [{"label": opt.label} for opt in section.options]

            # Add default for dropdowns
            if section.type == "dropdown" and section.default is not None:
                field["attributes"]["default"] = section.default

            # Validation
            field["validations"] = {"required": section.required}

        data["body"].append(field)

    return write_yaml(data, sort_keys=False, default_flow_style=False)


def _generate_options(section, lang: Language) -> list[str]:
    """Generate options from Language data sources"""
    options = []

    if section.source == "components":
        source_data = lang.components
    elif section.source == "spec_kinds":
        source_data = lang.spec_kinds
    elif section.source == "spec_status":
        source_data = list(SpecStatus)
    else:
        raise ValueError(f"Unknown source: {section.source}")

    for item in source_data:
        if section.format:
            # Build namespace for format string evaluation
            if section.source == "spec_status":
                ns = {"value": item.value}
            else:
                # Provide both regular and uppercase versions of string attributes
                ns = {
                    "id": item.id,
                    "ID": item.id.upper() if hasattr(item.id, 'upper') else item.id,
                    "name": item.name,
                    "NAME": item.name.upper() if hasattr(item.name, 'upper') else item.name,
                    "description": getattr(item, 'description', ''),
                    "DESCRIPTION": getattr(item, 'description', '').upper() if hasattr(getattr(item, 'description', ''), 'upper') else getattr(item, 'description', ''),
                    "code": getattr(item, 'code', ''),
                    "CODE": getattr(item, 'code', '').upper() if hasattr(getattr(item, 'code', ''), 'upper') else getattr(item, 'code', ''),
                    "category": getattr(item, 'category', ''),
                    "CATEGORY": getattr(item, 'category', '').upper() if hasattr(getattr(item, 'category', ''), 'upper') else getattr(item, 'category', ''),
                }

            try:
                formatted = section.format.format(**ns)
                options.append(formatted)
            except KeyError as e:
                raise ValueError(f"Format string '{section.format}' missing key {e} for {section.source}")
        else:
            # Default format
            if section.source == "components":
                options.append(item.id)
            elif section.source == "spec_kinds":
                options.append(f"{item.id.upper()} ({item.name})")
            elif section.source == "spec_status":
                options.append(item.value)

    return options


@app.command()
def normalize_ascii(
    dry_run: bool = typer.Option(False, "--dry-run", help="Show what would be changed without modifying files"),
    path: str = typer.Option(None, "--path", help="Specific file or directory to process (default: all markdown)")
):
    """
    Normalize Unicode box-drawing and special characters to ASCII equivalents in markdown files.

    This ensures maximum compatibility across editors, terminals, and documentation systems.
    """
    # Character replacement mapping
    REPLACEMENTS: Dict[str, str] = {
        # Box drawing characters
        '├': '|--',
        '│': '|',
        '└': '`--',
        '─': '-',
        '┤': '--|',
        '┬': '--+',
        '┴': '--+',
        '┼': '--+',
        '┌': ',--',
        '┐': '--.',
        '╭': ',--',
        '╮': '--.',
        '╰': '`--',
        '╯': '--\'',

        # Arrows
        '→': '->',
        '←': '<-',
        '↑': '^',
        '↓': 'v',
        '⇒': '=>',
        '⇐': '<=',

        # Bullets
        '•': '*',
        '◦': '-',
        '▪': '*',
        '▫': '-',
    }

    # Determine which files to process
    if path:
        target_path = Path(path)
        if not target_path.is_absolute():
            target_path = DOCS_ROOT / target_path
        if target_path.is_file():
            markdown_files = [target_path]
        elif target_path.is_dir():
            markdown_files = list(target_path.rglob("*.md"))
        else:
            typer.echo(f"Error: Path {path} does not exist", err=True)
            raise typer.Exit(1)
    else:
        # Process all markdown files in the repository
        markdown_files = list(DOCS_ROOT.rglob("*.md"))

    files_modified = 0
    total_replacements = 0

    for md_file in markdown_files:
        # Skip certain directories
        if any(skip in md_file.parts for skip in ['.git', 'node_modules', 'dist', '.next']):
            continue

        try:
            content = md_file.read_text(encoding='utf-8')
            original_content = content

            # Track replacements for this file
            file_replacements = []

            # Apply all replacements
            for unicode_char, ascii_equiv in REPLACEMENTS.items():
                if unicode_char in content:
                    count = content.count(unicode_char)
                    if count > 0:
                        file_replacements.append((unicode_char, ascii_equiv, count))
                        content = content.replace(unicode_char, ascii_equiv)

            # Only process if changes were made
            if content != original_content:
                files_modified += 1

                # Get relative path for display
                try:
                    display_path = md_file.relative_to(DOCS_ROOT)
                except ValueError:
                    display_path = md_file

                if dry_run:
                    typer.echo(f"\n{display_path}:")
                    for unicode_char, ascii_equiv, count in file_replacements:
                        total_replacements += count
                        typer.echo(f"  {unicode_char!r} -> {ascii_equiv!r} ({count} occurrence{'s' if count > 1 else ''})")
                else:
                    md_file.write_text(content, encoding='utf-8')
                    typer.echo(f"✓ Normalized {display_path}")
                    for unicode_char, ascii_equiv, count in file_replacements:
                        total_replacements += count

        except Exception as e:
            typer.echo(f"Error processing {md_file}: {e}", err=True)

    if dry_run:
        typer.echo(f"\nDry run complete: {total_replacements} replacements in {files_modified} file(s)")
        typer.echo("Run without --dry-run to apply changes")
    else:
        typer.echo(f"\nNormalized {files_modified} file(s) with {total_replacements} total replacements")


if __name__ == "__main__":
    app()
