import re
import typer
import difflib
from pathlib import Path

from auto.types import ROOT, SPEC_DIR, RSC, Language, Spec, DOCS_ROOT
from yaml import safe_dump as write_yaml

app = typer.Typer(
    name="doc-manager",
    help="Manage Kintsu documentation schemas and specifications.",
)

TEMPLATE_PATH = ROOT / "templates"

TEMPLATES = {
    "ad": TEMPLATE_PATH / "ad.md",
}


@app.command()
def spec_guide():
    lang = Language.get()
    lang.write_spec()


@app.command()
def collect_refs():
    """Collect cross-references between specifications and write to references.yaml"""
    # Pattern to match spec references like [RFC-0001](/specs/rfc/rfc-0001)
    # Case insensitive for spec kind
    pattern = re.compile(
        r'\[([A-Z]+)-0*(\d+)\]\(/specs/[a-z]+/[a-z]+-0*\d+\)',
        re.IGNORECASE
    )

    references: dict[str, set[str]] = {}

    # Walk all markdown files in specs directory
    for spec_file in SPEC_DIR.rglob("*.md"):
        content = spec_file.read_text()

        # Extract spec ID from filename (e.g., RFC-0001.md -> rfc-0001)
        filename = spec_file.stem  # e.g., RFC-0001
        parts = filename.split("-")
        if len(parts) == 2:
            source_kind = parts[0].lower()
            source_num = int(parts[1])
            source_id = f"{source_kind}-{source_num:04d}"

            # Find all references in this file
            matches = pattern.findall(content)
            if matches:
                refs = set()
                for kind, num in matches:
                    ref_id = f"{kind.lower()}-{int(num):04d}"
                    # Don't include self-references
                    if ref_id != source_id:
                        refs.add(ref_id)

                if refs:
                    references[source_id] = sorted(refs)

    # Write to references.yaml
    refs_path = RSC / "references.yaml"
    refs_path.write_text(
        "# @autogenerated - DO NOT EDIT\n\n" +
        write_yaml(dict(sorted(references.items())), sort_keys=False, default_flow_style=False)
    )

    print(f"Wrote references to {refs_path}")
    print(f"Collected {len(references)} specs with cross-references")


@app.command()
def new_spec(
    spec_kind: str = typer.Option(help="Specification kind ID"),
    title: str = typer.Option(help="Title of the new specification"),
    author: str = typer.Option(help="Author of the specification (github username)"),
    components: list[str] = typer.Option(
        help="Component IDs included in the specification"
    ),
):
    lang = Language.get()
    next_number = Spec.next_spec_number(spec_kind)

    spec = Spec.new(
        kind=spec_kind,
        number=next_number,
        title=title,
        author=author,
        components=components,
        version_after=lang.current_version,
    )

    lang.validate_spec(spec)

    print(f"Creating new spec {spec_kind}-{next_number} titled '{title}'")

    spec_kind_data = lang.get_spec_kind(spec_kind)
    template = spec_kind_data.template_for(lang)

    qualified_spec = f"{spec.kind}-{spec.number:04d}"

    out = spec.as_markdown_head() + template.format(
        qualified_spec=qualified_spec, **Spec.write_to_dict(spec)
    )

    path = spec.path_for()

    if not path.parent.exists():
        path.parent.mkdir()

    path.write_text(out)


@app.command()
def reference_tables(
    dry_run: bool = typer.Option(False, "--dry-run", help="Show diffs without writing files")
):
    """Update ## References sections in all specification files based on references.yaml"""

    lang = Language.get()
    refs = lang.references

    # Pattern to match the entire References section
    refs_section_pattern = re.compile(
        r'^## References\n(?:(?!^## ).*\n)*',
        re.MULTILINE
    )

    # Pattern to match existing reference lines
    ref_line_pattern = re.compile(
        r'- \[([A-Z]+-\d+)\]\(/specs/[a-z]+/[a-z]+-\d+\)',
        re.IGNORECASE
    )

    updated_count = 0

    for spec_file in SPEC_DIR.rglob("*.md"):
        content = spec_file.read_text()

        # Extract spec ID from filename
        filename = spec_file.stem
        parts = filename.split("-")
        if len(parts) != 2:
            continue

        source_kind = parts[0].lower()
        source_num = int(parts[1])
        source_id = f"{source_kind}-{source_num:04d}"

        # Check if this spec has references
        if source_id not in refs:
            continue

        # Find existing References section
        match = refs_section_pattern.search(content)
        if not match:
            # No References section found, skip
            continue

        existing_section = match.group(0)

        # Extract manually added references (ones not in references.yaml)
        existing_refs = set()
        for ref_match in ref_line_pattern.finditer(existing_section):
            ref_id = ref_match.group(1).lower()
            # Normalize to 4-digit format
            ref_parts = ref_id.split("-")
            if len(ref_parts) == 2:
                normalized = f"{ref_parts[0]}-{int(ref_parts[1]):04d}"
                existing_refs.add(normalized)

        # Get references from references.yaml
        yaml_refs = set(refs[source_id])

        # Find manually added refs (in file but not in yaml)
        manual_refs = existing_refs - yaml_refs

        # Combine: yaml refs + manual refs, sorted
        all_refs = sorted(yaml_refs | manual_refs)

        # Build new References section with proper titles
        new_section = "## References\n\n"
        for ref_id in all_refs:
            # Find the spec to get its title
            ref_parts = ref_id.split("-")
            ref_kind = ref_parts[0]
            ref_num = int(ref_parts[1])

            ref_path = SPEC_DIR / ref_kind / f"{ref_kind.upper()}-{ref_num:04d}.md"
            if ref_path.exists():
                # Extract title from the spec file
                ref_content = ref_path.read_text()
                try:
                    ref_spec = Spec.from_markdown_head(ref_content)
                    title = ref_spec.title
                except:
                    # Fallback if parsing fails
                    title = "Unknown"
            else:
                title = "Unknown"

            # Format: [RFC-0001](/specs/rfc/rfc-0001) - Title
            display_id = f"{ref_kind.upper()}-{ref_num:04d}"
            url_id = f"{ref_kind.lower()}-{ref_num:04d}"
            new_section += f"- [{display_id}](/specs/{ref_kind}/{url_id}) - {title}\n"

        new_section += "\n"

        # Replace the old References section
        new_content = refs_section_pattern.sub(new_section, content)

        if new_content != content:
            if dry_run:
                # Show diff
                old_lines = content.splitlines(keepends=True)
                new_lines = new_content.splitlines(keepends=True)
                diff = difflib.unified_diff(
                    old_lines,
                    new_lines,
                    fromfile=f"a/{spec_file.relative_to(DOCS_ROOT)}",
                    tofile=f"b/{spec_file.relative_to(DOCS_ROOT)}",
                    lineterm=""
                )
                print("".join(diff))
            else:
                spec_file.write_text(new_content)
                print(f"Updated references in {spec_file.name}")
            updated_count += 1

    if dry_run:
        print(f"\nWould update {updated_count} specification files (dry-run mode)")
    else:
        print(f"\nUpdated {updated_count} specification files")


@app.command()
def collect_specs():
    """Generate specification summary with nested sub-references"""
    lang = Language.get()
    specs = lang.specs()
    refs = lang.references

    summary = "---\n# @autogenerated - DO NOT EDIT\n\ntitle: Specifications\n---\n\n"
    by_category: dict[str, list[Spec]] = {}
    for spec in specs:
        if spec.kind in by_category:
            by_category[spec.kind].append(spec)
        else:
            by_category[spec.kind] = [spec]

    for spec_kind, specs_list in by_category.items():
        category = lang.get_spec_kind(spec_kind)

        summary += f"- [{category.name}](/specs/{spec_kind.lower()})\n"
        for spec in specs_list:
            spec_id = spec.qualified_id()
            spec_id_lower = spec_id.lower()  # Match references.yaml format
            summary += f"  - [{spec_id} - {spec.title}]({spec.url_for()})\n"

            # Add sub-references if they exist (references.yaml uses lowercase)
            if spec_id_lower in refs:
                for ref_id in refs[spec_id_lower]:
                    # Find referenced spec to get its title
                    ref_parts = ref_id.split("-")
                    ref_kind = ref_parts[0]
                    ref_num = int(ref_parts[1])

                    ref_path = SPEC_DIR / ref_kind / f"{ref_kind.upper()}-{ref_num:04d}.md"
                    if ref_path.exists():
                        try:
                            ref_content = ref_path.read_text()
                            ref_spec = Spec.from_markdown_head(ref_content)
                            title = ref_spec.title
                        except:
                            title = "Unknown"
                    else:
                        title = "Unknown"

                    display_id = f"{ref_kind.upper()}-{ref_num:04d}"
                    url = f"/specs/{ref_kind}/{ref_id}"
                    # Use 4 spaces and hyphen for proper nesting (not 6 spaces and asterisk)
                    summary += f"    - [{display_id} - {title}]({url})\n"
        summary += "\n"

    summary_path = SPEC_DIR / "../docs" / "summary.md"
    summary_path.write_text(summary)
    print(f"Wrote spec summary to {summary_path}")


if __name__ == "__main__":
    app()
