#!/usr/bin/env bun
/**
 * Harper Grammar Check Script
 *
 * This script manages Harper dictionary generation and runs grammar checks
 * with Canadian English dialect on markdown files.
 *
 * Features:
 * - Generates case variants (Title Case, lowercase, UPPERCASE) for base words
 * - Bans American spellings by marking them as incorrect
 * - Runs Harper with appropriate ignores for documentation style
 */

import { execSync } from "child_process";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const DICT_PATH = resolve(REPO_ROOT, ".harper-dictionary.txt");
const GENERATED_DICT_PATH = resolve(
  REPO_ROOT,
  ".harper-dictionary-generated.txt",
);

// Base words (Canadian spellings only)
const BASE_WORDS = [
  // Project-specific
  "Kintsu",
  "Astro",
  "Starlight",
  // Spec kinds
  "TSY",
  "SPEC",
  "ERR",
  "RFC",
  "AD",
  // Formats
  "MDX",
  // Terms
  "frontmatter",
  "implementability",
  "mise",
  "Markdown",
  // Canadian English spellings (will ban American equivalents)
  "serialisation",
  "deserialisation",
  "normalisation",
  "initialisation",
  "behaviour",
  "colour",
  "favourite",
  "honour",
  "neighbour",
  "centre",
  "licence",
  "defence",
  "offence",
  "analyse",
  "recognise",
  "organise",
  "categorise",
  "optimise",
  "specialise",
  "generalise",
  "customise",
  "standardise",
  "realise",
  "minimise",
  "maximise",
  "visualise",
  "utilise",
  "prioritise",
  "characterise",
  "emphasise",
  "parameterise",
  "categorisation",
  "synchronisation",
  // Compound words
  "multi-layered",
];

// American spellings to ban (map to Canadian)
const BANNED_AMERICAN: Record<string, string> = {
  serialization: "serialisation",
  deserialization: "deserialisation",
  normalization: "normalisation",
  initialization: "initialisation",
  behavior: "behaviour",
  color: "colour",
  favorite: "favourite",
  honor: "honour",
  neighbor: "neighbour",
  center: "centre",
  license: "licence",
  defense: "defence",
  offense: "offence",
  analyze: "analyse",
  recognize: "recognise",
  organize: "organise",
  categorize: "categorise",
  optimize: "optimise",
  specialize: "specialise",
  generalize: "generalise",
  customize: "customise",
  standardize: "standardise",
  realize: "realise",
  minimize: "minimise",
  maximize: "maximise",
  visualize: "visualise",
  utilize: "utilise",
  prioritize: "prioritise",
  characterize: "characterise",
  emphasize: "emphasise",
  parameterize: "parameterise",
  categorization: "categorisation",
  synchronization: "synchronisation",
  parameterized: "parameterised",
};

/**
 * Generate case variants for a word
 */
function generateCaseVariants(word: string): string[] {
  const variants = new Set<string>();

  // Original
  variants.add(word);

  // Lowercase
  variants.add(word.toLowerCase());

  // Uppercase (only if not already uppercase)
  if (word !== word.toUpperCase()) {
    variants.add(word.toUpperCase());
  }

  // Title case (first letter uppercase)
  const titleCase = word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  if (titleCase !== word) {
    variants.add(titleCase);
  }

  // Possessive forms
  if (!word.endsWith("'") && !word.endsWith("s")) {
    variants.add(`${word}'s`);
    variants.add(`${word.toLowerCase()}'s`);
  }

  // Past tense for verbs ending in 'e'
  if (word.endsWith("e") && word.length > 3) {
    variants.add(`${word}d`);
    variants.add(`${word.toLowerCase()}d`);
  }

  return Array.from(variants);
}

/**
 * Generate the Harper dictionary
 */
function generateDictionary(): void {
  const lines: string[] = [];

  // Add header comment
  lines.push("# Auto-generated by scripts/harper-check.ts");
  lines.push("# Base words with case variants");
  lines.push("");

  // Generate variants for all base words
  const allWords = new Set<string>();
  for (const word of BASE_WORDS) {
    const variants = generateCaseVariants(word);
    for (const variant of variants) {
      allWords.add(variant);
    }
  }

  // Sort and add to dictionary
  const sortedWords = Array.from(allWords).sort((a, b) => {
    // Case-insensitive sort, but prioritize Title Case
    const aLower = a.toLowerCase();
    const bLower = b.toLowerCase();
    if (aLower === bLower) {
      // If same word different case, Title Case first
      if (a[0] === a[0].toUpperCase() && b[0] === b[0].toLowerCase()) return -1;
      if (b[0] === b[0].toUpperCase() && a[0] === a[0].toLowerCase()) return 1;
      return a.localeCompare(b);
    }
    return aLower.localeCompare(bLower);
  });

  lines.push(...sortedWords);
  lines.push("");

  // Add banned American spellings section
  lines.push("# Banned American spellings (redirect to Canadian)");
  lines.push("# These will be flagged as errors");
  lines.push("");

  // Harper doesn't support banning words directly via dictionary
  // We'll document them here for reference
  for (const [american, canadian] of Object.entries(BANNED_AMERICAN)) {
    lines.push(`# ${american} -> ${canadian}`);
  }

  writeFileSync(GENERATED_DICT_PATH, lines.join("\n") + "\n");
  console.log(`✓ Generated dictionary with ${sortedWords.length} words`);
  console.log(
    `✓ Documented ${Object.keys(BANNED_AMERICAN).length} banned American spellings`,
  );
}

/**
 * Run Harper linter on markdown files
 */
function runHarper(files?: string[]): void {
  const ignoreRules = [
    "SentenceCapitalization", // Too strict for list items
    "UseTitleCase", // Too strict for headings
    "OrthographicConsistency", // Conflicts with Canadian vs American
  ];

  let targetFiles: string[];

  if (files && files.length > 0) {
    targetFiles = files;
  } else {
    // Find all markdown files
    try {
      const findCmd =
        "find src/content -name '*.md' -o -name '*.mdx' | grep -v 'node_modules' | grep -v 'kintsu/' | grep -v 'factsets/'";
      const output = execSync(findCmd, { cwd: REPO_ROOT, encoding: "utf-8" });
      targetFiles = output.trim().split("\n").filter(Boolean);
    } catch (error) {
      console.error("Failed to find markdown files");
      process.exit(1);
    }
  }

  if (targetFiles.length === 0) {
    console.log("No markdown files to check");
    return;
  }

  console.log(`\nChecking ${targetFiles.length} markdown file(s)...\n`);

  const ignoreArgs = ignoreRules.map((rule) => `--ignore ${rule}`).join(" ");
  const cmd = `harper-cli lint --dialect Canadian --user-dict-path ${GENERATED_DICT_PATH} ${ignoreArgs} ${targetFiles.join(" ")}`;

  try {
    execSync(cmd, { cwd: REPO_ROOT, stdio: "inherit" });
    console.log("\n✓ No grammar issues found");
  } catch (error) {
    console.error("\n✗ Grammar issues found");
    process.exit(1);
  }
}

// Main execution
const args = process.argv.slice(2);
const command = args[0];

switch (command) {
  case "generate":
    generateDictionary();
    break;
  case "check":
    generateDictionary();
    runHarper(args.slice(1));
    break;
  case "lint":
    if (!existsSync(GENERATED_DICT_PATH)) {
      console.log("Dictionary not found, generating...");
      generateDictionary();
    }
    runHarper(args.slice(1));
    break;
  default:
    console.log(`
Harper Grammar Checker

Usage:
  bun scripts/harper-check.ts generate          Generate dictionary only
  bun scripts/harper-check.ts check [files...]  Generate + check files
  bun scripts/harper-check.ts lint [files...]   Check files (use existing dictionary)

Examples:
  bun scripts/harper-check.ts generate
  bun scripts/harper-check.ts check
  bun scripts/harper-check.ts check README.md
  bun scripts/harper-check.ts lint src/content/docs/**/*.md
		`);
    process.exit(command ? 1 : 0);
}
